version: "3.9"

services:
  react-app:
    image: node:20-alpine
    container_name: react-builder
    working_dir: /app
    volumes:
      - ./frontend:/app   # React का कोड mount किया
      - /app/node_modules
    command: sh -c "npm install && npm run build && cp -r build/* /usr/share/nginx/html/"
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "80:80"   # Browser में localhost:80 पर दिखेगा
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /usr/share/nginx/html
    restart: always
