const Urls = {
    // baseURL: "",
    // baseURL: "https://cautionapi.mpulsenet.com",
    // baseURL: "http://127.0.0.1:5000",
    downloadbaseURL: "http://127.0.0.1:5000",
    baseURL: "https://api.mpulsenet.dataplus.live",
    // downloadbaseURL: "https://api.mpulsenet.dataplus.live",
    // baseURL: "https://api.vedang.dataplus.live",
    // downloadbaseURL: "https://api.vedang.dataplus.live",
    signin: "/login",
    signup: "/register",
    getBCGCS: '/client/getBCGCS',
    signout: "/logout",
    refresh: "/refresh",
    roles: '/roles',
    users:'/users',
    register_users:'/register',
    user_scripting_files:'/user-scripting-files',
    get_gpl_audit_files:'/gpl_audit_files',
    
    migrationList:'/migrationList',
    setpassword: '/setuppassword/stepOne',
    verify:"/api/verify-email",
    registeradmin:'/api/register-admin',
    companylist:'/api/companylist',
    getmembership:'/api/membership',
    fanclub:'/api/fanclublist',
    updatemember:"/api/update-member",
    campaign:"/api/campaign",
    patchcampaign:"/api/campaign/verify",
    isblocked:"/api/user-block",
    extract:"extract-page",
    files:"/files",
    dashboard:"/dashboard",
    analyze:"/analyze",
    urlfiles:"/user-files",
    urlenmfiles:"/user-enm-files",
    upload:"/upload",
    uploadenm:"/uploadenm",
    uploadScripting:"/uploadScripting",
    gplauditNokiauploadScripting:"/uploadScripting",
    gplauditNokiaSetting:"/run_gpl_audit_nokia",
    gplaudituploadScripting:"/run_gpl_audit",
    emns:"/enms",
    circles:"/circles",
    sidebarlinks:"/sidebar-links",
    enmcount:"/user-enm-files/count",
    mlistcount:"/migrationList/count",
    uscriptcount:"/user-scripting-files/count",
    userfilescount:"/user-files/count"
    


    
}

export default Urls